### ISSUE TITLE
Nuxt-edge is not supported

### ISSUE THREAD

**Issue by gianniskarmas** [potato4d/nuxt-maintenance-mode#114]
App 19318 output:   Error: Cannot find module 'nuxt'
App 19318 output:   Require stack:
App 19318 output:   - node_modules/nuxt-maintenance-mode/lib/middleware.js
App 19318 output:   - node_modules/nuxt-maintenance-mode/lib/module.js
App 19318 output:   - node_modules/@nuxt/core-edge/dist/core.js
App 19318 output:   - node_modules/@nuxt/cli-edge/dist/cli-index.js
App 19318 output:   - node_modules/@nuxt/cli-edge/dist/cli.js
App 19318 output:   - node_modules/nuxt-start-edge/bin/nuxt-start.js
App 19318 output:   - /usr/share/passenger/helper-scripts/node-loader.js
App 19318 output:   at Object.<anonymous> (node_modules/nuxt-maintenance-mode/lib/middleware.js:35:26)
App 19318 output:   at Generator.next (<anonymous>)
App 19318 output:   at node_modules/nuxt-maintenance-mode/lib/middleware.js:7:71
App 19318 output:   at new Promise (<anonymous>)
App 19318 output:   at __awaiter (node_modules/nuxt-maintenance-mode/lib/middleware.js:3:12)
App 19318 output:   at node_modules/nuxt-maintenance-mode/lib/middleware.js:34:32
App 19318 output:   at call (node_modules/connect/index.js:239:7)
App 19318 output:   at next (node_modules/connect/index.js:183:5)
App 19318 output:   at next (node_modules/connect/index.js:161:14)
App 19318 output:   at next (node_modules/connect/index.js:161:14) (repeated 1 times)

**Comment by potato4d** [comment]
Thank you for your report.
I'll check it soon.

**Comment by jhull** [comment]
Would love to have this as an option too...
